name: CI build for docker custom action
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: run my custom docker container
        id: custom-faizan-action
        uses: ./hello-world-docker-action
        with: 
          who-to-greet: "Faizan Ahmad from Volo"

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
