name: Faizan's first hands-on workflow
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo "This was triggered by this event ${{ github.event_name }}"
      - run: echo "This was triggered by this branch ${{ github.ref }}"
      - run: echo "This repo has this files"
      - run: tree
